### PR TITLE
Houdini: Improve load image (colorspace, single file, switch, more products)

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Tweak the Houdini Image COP2 loader.

- Support setting OCIO colorspace
- Support single frame file versus sequence
- Support 'switch' folder functionality
- Allow loading more product types

## Additional info

Note that the colorspace is only set if any colorspace data was published along with the representation.
(This might need to be tested in AYON since I'm not entirely sure that's still stored in `data` of the representation?)

## Testing notes:

1. Loading images should work
2. Loading images with colorspace data in representation should set the OCIO colorspace on the node.

### CODE REVIEW

**Review by MustafaJafar — APPROVED** [review]
I tested loading `image` and `imagesequence` 
These work on my side 
- Support single frame file versus sequence
- Support 'switch' folder functionality
- Allow loading more product types

I don't currently have any `imagesequences` with `OCIO` for testing. 
A question: 
OCIO options are quite limited, aren't they ? (I don't know much tbh this is what I can find in file load)
image

**Comment by BigRoy** [comment]
> I tested loading `image` and `imagesequence` These work on my side
> 
>     * Support single frame file versus sequence
> 
>     * Support 'switch' folder functionality
> 
>     * Allow loading more product types
> 
> 
> I don't currently have any `imagesequences` with `OCIO` for testing. A question: OCIO options are quite limited, aren't they ? (I don't know much tbh this is what I can find in file load) image

Likely you don't have the `OCIO` entry in the drop down menu because you've not set an `OCIO` env var which is likely due to not having OCIO configured in project settings?

**Review by moonyuet — APPROVED** [review]

**Comment by moonyuet** [comment]
General code looks good for me. Haven't tested in Houdini btw(I dont have houdini in my current laptop). @MustafaJafar Maybe you can try to enable the setting first to see if it is updated as expected. It should be working if there is no any error spotted in Houdini. But if there is error, the line below should need some tweaks. Otherwise it should be good and ready for merge. 
https://github.com/ynput/ayon-core/blob/4ba0259e5f97f8137d1f8c1caab80d3d511e4725/client/ayon_core/hosts/houdini/plugins/load/load_image.py#L176-L179

**Comment by MustafaJafar** [comment]
I believe I have OCIO enabled in my settings. 
and I think if my sequence includes OCIO data then `"ocio_space": colorspace` won't work properly. I have Houdini 19.5!  

image

**Comment by BigRoy** [comment]
> I believe I have OCIO enabled in my settings. and I think if my sequence includes OCIO data then `"ocio_space": colorspace` won't work properly. I have Houdini 19.5!
> 
> image

Thanks - this seems Hou 20+ only?

Hou 20
image

Hou 19.5
image

---

I suppose I'll need to add a version check ;)

**Review by MustafaJafar — APPROVED** [review]
This is so cool! 
It works on my side. 
[I didn't test loading representation with colordata as 
1. I don't have publishes with colordata 
2. I'm using Hou 19.5 ]

**Pull request merged**
