### PR TITLE
Chore: Houdini refactor to generic ExtractROP plug-in

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Improve code re-use and implement a more generic ROP node extractor used by those families for which it applies.

This makes sure that they remain sync in implementation instead of being scattered and helps focusing the implementation on this single plug-in instead simplifying maintenance.

## Additional info

This also implements #675 but also generalizes it into a single plug-in instead. (with some subclasses where code deviated)

Fixes https://github.com/ynput/ayon-core/issues/672

## Testing notes:

1. Publishing all the product types should work for single frames and multiple frames:

- [x] abc
- [x] camera
- [x] bgeo
  - [x] bgeo works with hero versions (Hero version integration fails for bgeo; known issue? see [here](https://community.ynput.io/t/hero-publishing-udims/1451/3?u=bigroy) and https://github.com/ynput/ayon-backend/pull/252) 
- [x] pointcache
- [x] fbx
- [x] imagesequence
- [x] vdbcache
- [ ] ass
- [ ] redshiftproxy
- [x] mantraifd

2. [x] The above families that support it also work for farm submissions. 
  - note: pointcache farm submission is broken, but that's also in `develop`

### CODE REVIEW

**Comment by MustafaJafar** [comment]
This is cool! 
I believe implementing render target with other products will help generalizing the extraction.

**Comment by MustafaJafar** [comment]
I gave it a shot. tested few product types and they worked fine. 
Also, out of curiosity, I tried to publish pointcache to farm, I got this error 
```
Traceback (most recent call last):
  File "C:\Users\Mustafa Taher\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406142259_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "E:\Ynput\ayon-core\server_addon\deadline\client\ayon_deadline\plugins\publish\submit_publish_cache_job.py", line 285, in process
    instances = create_instances_for_cache(
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\farm\pyblish_functions.py", line 942, in create_instances_for_cache
    raise ValueError("Found multiple non related files "
ValueError: Found multiple non related files to render, don't know what to do with them.
```

**Comment by BigRoy** [comment]
> I gave it a shot. tested few product types and they worked fine. Also, out of curiosity, I tried to publish pointcache to farm, I got this error
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Mustafa Taher\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406142259_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
>     runner(*args)
>   File "E:\Ynput\ayon-core\server_addon\deadline\client\ayon_deadline\plugins\publish\submit_publish_cache_job.py", line 285, in process
>     instances = create_instances_for_cache(
>   File "E:\Ynput\ayon-core\client\ayon_core\pipeline\farm\pyblish_functions.py", line 942, in create_instances_for_cache
>     raise ValueError("Found multiple non related files "
> ValueError: Found multiple non related files to render, don't know what to do with them.
> ```

Lovely! I've never tried the farm submissions. Does it work outside of this PR? (I suppose not?)

**Comment by BigRoy** [comment]
@moonyuet any chance you can also push this through a test-run?

**Comment by moonyuet** [comment]
> @moonyuet any chance you can also push this through a test-run?

I try with publishing fbx. Errored out.
image

Successfully submitted mantra ifd(local and farm)
image

image
image

**Comment by BigRoy** [comment]
> I try with publishing fbx. Errored out.

Fixed with https://github.com/ynput/ayon-core/pull/676/commits/187b2e98c53e49819c807eab9829f436b16af676

**Comment by moonyuet** [comment]
There is also an issue with camera publishing
image
pointcache local publish ok
Encounter same issue with mustafa when testing pointcache farm publish

**Comment by BigRoy** [comment]
> There is also an issue with camera publishing

Fixed with https://github.com/ynput/ayon-core/pull/676/commits/32ebf9c34f91e8f4cc88ed6f98d97c2d6d600fd5 - sorry about that. I kept the extractor list next to it and I still missed that it lacked `camera`. Just proves once again that I should always rely on the computer to tell me the differences between the lists. :D

> Encounter same issue with mustafa when testing pointcache farm publish

I have a feeling this issue may exist outside of this PR as well - I don't have Deadline configured on my dev setup currently. Anyone of you able to confirm this quickly using `develop`?

**Comment by BigRoy** [comment]
I'd say looking at the tests this should be safe to merge.

**Review by moonyuet — APPROVED** [review]

**Pull request merged**
