### PR TITLE
Maya: Load RenderSetup add more options

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Maya Load Rendersetup with more options:
- allow loading unmanaged 
- automatically 'accept' the import 
- pick import mode

## Additional info

n/a

## Testing notes:

1. Loading RenderSetup to maya should work.

### CODE REVIEW

**Review by LiborBatek — COMMENTED** [review]
When applying the ```renderSetup``` product aka loading it via ```Loader``` Im getting an error message however those settings in JSON got applied to my workfile...

image

```Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_rendersetup.py", line 114, in load
    asset = context['asset']['name']
KeyError: 'asset'
```

**Comment by BigRoy** [comment]
> When applying the `renderSetup` product aka loading it via `Loader` Im getting an error message however those settings in JSON got applied to my workfile...
> image
> 
> ```
>   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
>     load_with_repre_context(
>   File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
>     return loader.load(repre_context, name, namespace, options)
>   File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_rendersetup.py", line 114, in load
>     asset = context['asset']['name']
> KeyError: 'asset'
> ```

Sorry, my bad. Fixed with https://github.com/ynput/ayon-core/pull/310/commits/27d531536c779561ad6b0573be226eaf70e86b1b

**Review by tokejepsen — CHANGES_REQUESTED** [review]
Could you elaborate on what this resolves that is not in current `develop`?

I tried loading in a `renderSetup` and I dont get any import dialog.

**Comment by BigRoy** [comment]
> Could you elaborate on what this resolves that is not in current `develop`?

Without this PR by default any loaded rendersetup layers will be visually 'cursive/italic' in the render setup manager and still need to be marked "accepted" after the import. This PR exposes an option to accept them automatically, which is now enabled by default.

> I tried loading in a `renderSetup` and I dont get any import dialog.

The option box should be on the Load option in the Loader. (The option box on the right side of the loader action).

---

Does that answer your question @tokejepsen ?

**Review by tokejepsen — APPROVED** [review]
Tested successfully in Maya 2023.

**Review by LiborBatek — APPROVED** [review]
Did another test round and this time no any errors given.

image

**Pull request merged**
