### PR TITLE
Houdini: Fix CreateHDA for Houdini 20+

### LINKED ISSUE #697: Houdini: Cannot import name 'setToolSubmenu' from 'assettools'
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Recently the CreateHDA logic has been changed to use a `assettools.setToolSubmenu` function. However, in Houdini 20.0.724 I'm getting this error:

```
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "E:\dev\ayon-core\server_addon\houdini\client\ayon_houdini\plugins\create\create_hda.py"
Traceback (most recent call last):
  File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\dev\ayon-core\server_addon\houdini\client\ayon_houdini\plugins\create\create_hda.py", line 4, in <module>
    from assettools import setToolSubmenu
ImportError: cannot import name 'setToolSubmenu' from 'assettools' (C:\PROGRA~1/SIDEEF~1/HOUDIN~1.724/houdini/python3.10libs\assettools.py)
```

The relevant PR that added the import is https://github.com/ynput/ayon-core/pull/644

### Expected Behavior:

It should not error.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Launch Houdini 20.0.742 in AYON
2. Check output in Houdini console.
3. In publisher create tab the "Create HDA" also is not listed (because it errors)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "E:\dev\ayon-core\server_addon\houdini\client\ayon_houdini\plugins\create\create_hda.py"
Traceback (most recent call last):
  File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "E:\dev\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\dev\ayon-core\server_addon\houdini\client\ayon_houdini\plugins\create\create_hda.py", line 4, in <module>
    from assettools import setToolSubmenu
ImportError: cannot import name 'setToolSubmenu' from 'assettools' (C:\PROGRA~1/SIDEEF~1/HOUDIN~1.724/houdini/python3.10libs\assettools.py)
```

### Additional context:

_No response_

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Fix CreateHDA import, refactor `setToolSubmenu` -> `setTabSubMenu` for recent Houdini versions

## Additional info

Fixes #697

## Testing notes:

1. No errors should show upon startup of Houdini, in both Houdini 19 and 20
2. Create HDA and publishing should work in Houdini 19 and 20

### CODE REVIEW

**Review by MustafaJafar — CHANGES_REQUESTED** [review]
So, it works without issues but I noticed something weird. 
HDAs published from Houdini 20.0 don't keep their submenu. 
image

**Comment by MustafaJafar** [comment]
Yeah, they are not the same. 
Also, I wonder who are `Attila` and `Jeff` 
image

**Comment by MustafaJafar** [comment]
> Could you show what it looks like when published from Houdini 20?
> Also, do you need me to debug why this is happening and fix it? or are you looking into it?

I update my comment above and added a quick screen record. 
Currently, I'm comparing the two functions.

**Comment by BigRoy** [comment]
> Also, I wonder who are `Attila` and `Jeff`

Very likely:
- [Attila Torok](https://www.linkedin.com/in/attila-torok-25276633)
- [Jeff Wagner](https://www.linkedin.com/in/jeff-wagner-8a038a/)

**Comment by MustafaJafar** [comment]
> > Also, I wonder who are `Attila` and `Jeff`
> 
> Very likely:
> 
> * [Attila Torok](https://www.linkedin.com/in/attila-torok-25276633)
> * [Jeff Wagner](https://www.linkedin.com/in/jeff-wagner-8a038a/)

😮😮😮

**Comment by MustafaJafar** [comment]
@fabiaserra could you let us know what do you think about setting HDA's submenu location ? 
I found this some time ago [Setting HDA tab submenu name via python?](https://www.sidefx.com/forum/topic/85634/?page=1#post-370501) which is similar to `assettools.setToolSubmenu` logic in Houdini 19.5. 

For context, 
`assettools.setToolSubmenu` in Hou 19.5 was refactored to `assettools.setTabSubMenu` in Hou 20.0
`assettools.setToolSubmenu` sets the sub menu location permanently 
while `assettools.setTabSubMenu` sets the sub menu interactively (which requires the user to click apply in the HDA type properties window)

For reference, 
I used to use the same logic as `assettools.setTabSubMenu` but I replaced it with `assettools.setToolSubmenu`.
https://github.com/ynput/ayon-core/commit/17ec19f5069860be184733254db79f4a86308de5

**Comment by fabiaserra** [comment]
> @fabiaserra could you let us know what do you think about setting HDA's submenu location ?

I'm not sure what do you want me to check?

**Review by MustafaJafar — APPROVED** [review]
wow, it works! 

| workfile | loaded in another file |
|--|--|
| image | image |
| image | image |

**Comment by BigRoy** [comment]
Thanks for merging - be aware that this PR did not have a version bump which it should have. If we merge the USD one now quickly we should be fine - then it'd just contain both in one version bump.

**Pull request merged**
