### PR TITLE
Deadline: Version GlobalJobPreLoad

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Add version that is printed in GlobalJobPreLoad plugin.

## Additional info
Sometimes it is hard to debug issues with the plugin, with version printed in the log it should be a little bit easier.

## Testing notes:
1. Copy new plugin to deadline repository
2. Version should be printed in the job logs

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Yes, please!

**Comment by iLLiCiTiT** [comment]
@MustafaJafar 's idea https://github.com/ynput/ayon-core/pull/33#issuecomment-1939282124

**Comment by BigRoy** [comment]
> @MustafaJafar 's idea [#33 (comment)](https://github.com/ynput/ayon-core/pull/33#issuecomment-1939282124)

It's not a new idea - it has been proposed before.

- https://github.com/ynput/OpenPype/pull/5815#issuecomment-1786739056
- https://github.com/ynput/OpenPype/issues/5920
- https://github.com/ynput/OpenPype/issues/5919

Anyway, happy to see it implemented!

**Comment by iLLiCiTiT** [comment]
> Note that there I also recommended doing the same with the Ayon deadline plug-in so that also reports its version in the Ayon publisher logs, etc.

Good point, do you know how it can be printed in the plugin?

Something like this?
```python
def InitializeProcess(self):
    self.LogInfo("Initializing process with AYON plugin {}".format(__version__))
```

**Comment by BigRoy** [comment]
> > Note that there I also recommended doing the same with the Ayon deadline plug-in so that also reports its version in the Ayon publisher logs, etc.
> 
> Good point, do you know how it can be printed in the plugin?
> 
> Something like this?
> 
> ```python
> def InitializeProcess(self):
>     self.LogInfo("Initializing process with AYON plugin {}".format(__version__))
> ```

I believe that should work, yes.

They seem to be doing that in some of their plug-ins as well, e.g.

`3dsCmd`
```python
    def InitializeProcess( self ):
        # type: () -> None
        """
        Called by Deadline to initialize the process.
        Sets the plugin specific settings.
        """
        self.LogInfo( "3dsCmd Plugin Initializing..." )
```

They never log anything in `__init__` or alike, so I feel `InitializeProcess` is the best place, yes.
In the Maya Plug-in they do this in `StartJob` method:
```
        self.LogInfo( "Rendering with Maya Version " + str(self.Version) )
```
Nonetheless - I still think `InitializeProcess` might be the better candidate here.

**Review by kalisp — APPROVED** [review]
Works 
image

**Comment by BigRoy** [comment]
> Works image

@kalisp Can you also confirm the AYON plug-in getting reported?

**Pull request merged**
