### PR TITLE
Anatomy: Use AYON template categories

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Modify `Anatomy` to use AYON structure of anatomy templates.

## Additional info
AYON does support categories of templates which was "hacked" for OpenPype to work the same way as did in OpenPype, from this PR that changes and AYON structure is default behavior of `Anatomy`. That required to add additional level to anatomy data, but rather than using the templates structure as dictionary were added some methods that could help with that. Anatomy file was changed to a folder module to avoid huge single file content.

Instead of using `anatomy.templates_object["publish"]["default"]["path"]` it is used `anatomy.get_template_item("publish", "default", "path")`. Changed default template keys to be `"default"` instead of `"publish"`, `"hero"` etc. . Rename `"folder"` key to `"directory"` to match project entity model, but both are compatible for now. Key `"path"` is added automatically.

Settings for publish templates should be backwards compatible so `"publish_render"` should still work instead of `"render"`. But any code must be modified to use the category name.
- `anatomy.templates_obj["publish"]` > `anatomy.get_template_item("publish", "default")`
- `anatomy.templates_obj["publish_render"]` > `anatomy.get_template_item("publish", "render")`

### Byproduct changes
Removed `TemplatesDict` from `ayon_core.lib.path_templates` as it was used only by `Anatomy` but is not needed anymore and moved `TemplatesResultDict` to anatomy.

## Testing notes:
1. Template profiles can from now on use template key names without prefixes (`publish_` or `hero_`) but old setting should work too.
2. Workfile paths should be filled correctly.
3. Publish standard and hero versions should use correct templates and output paths.

### CODE REVIEW

**Comment by LiborBatek** [comment]
Giving me error during Ayon Launcher loading...

```*** WRN: >>> { loader_tool }: [  Couldn't load Loader tool for tray.  ]
==============================
expected an indented block (templates.py, line 383)
==============================
Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\modules\loader_action.py", line 16, in tray_init
    from ayon_core.tools.loader.ui import LoaderWindow
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\__init__.py", line 1, in <module>
    from .control import LoaderController
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\control.py", line 7, in <module>
    from ayon_core.pipeline import Anatomy, get_current_context
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\__init__.py", line 9, in <module>
    from .anatomy import Anatomy
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\anatomy\__init__.py", line 7, in <module>
    from .anatomy import Anatomy
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\anatomy\anatomy.py", line 15, in <module>
    from .templates import AnatomyTemplates
  File "C:\Program Files\Ynput\AYON 1.0.1\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\anatomy\templates.py", line 383
    class AnatomyTemplates:
    ^
IndentationERROR: expected an indented block
```

**Comment by LiborBatek** [comment]
Now ```Loader``` is working but another error when trying to launch ```maya``` host app...

```
*** WRN: >>> { app_maya/2024 }: [  ERROR in anatomy.format: 'NoneType' object has no attribute 'format_strict'  ]
==============================
ERROR in anatomy.format: 'NoneType' object has no attribute 'format_strict'
==============================
Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 1746, in prepare_context_environments
    workdir = get_workdir_with_workdir_data(
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\workfile\path_resolving.py", line 140, in get_workdir_with_workdir_data
    output = template_obj.format_strict(workdir_data)
AttributeERROR: 'NoneType' object has no attribute 'format_strict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\launcher\models\actions.py", line 126, in process
    self.application.launch(
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 361, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 506, in launch
    return self.launch_with_context(context)
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 482, in launch_with_context
    return launch_context.launch()
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 1291, in launch
    self.run_prelaunch_hooks()
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 1275, in run_prelaunch_hooks
    prelaunch_hook.execute()
  File "C:\Work\REPO\ayon-core\client\ayon_core\hooks\pre_global_host_data.py", line 46, in execute
    prepare_context_environments(temp_data)
  File "C:\Work\REPO\ayon-core\client\ayon_core\lib\applications.py", line 1754, in prepare_context_environments
    raise ApplicationLaunchFAILED(
ayon_core.lib.applications.ApplicationLaunchFAILED: ERROR in anatomy.format: 'NoneType' object has no attribute 'format_strict'
```

**Comment by iLLiCiTiT** [comment]
It looks like I forgot to push some changes last week.

**Comment by LiborBatek** [comment]
Getting error in ```maya``` and ```model``` publishing on ```Integrate Asset```

```
DEBUG: Establishing staging directory @ C:\Users\lbate\AppData\Local\Temp\pyblish_tmp_9m6r1umu
DEBUG: Looking for matching profile for: hosts: "maya" | product_types: "model" | task_names: "modeling" | task_types: "Modeling"
DEBUG: "model" not found in "product_types": ['review', 'render', 'prerender']
DEBUG: "maya" not found in "hosts": ['standalonepublisher']
DEBUG: "model" not found in "product_types": ['staticMesh', 'skeletalMesh']
DEBUG: "maya" not found in "hosts": ['traypublisher']
DEBUG: "maya" not found in "hosts": ['max']
DEBUG: "maya" not found in "hosts": ['blender']
DEBUG: Profile selected: {'product_types': [], 'hosts': [], 'task_types': [], 'task_names': [], 'template_name': 'publish'}
DEBUG: Product: modelMain
DEBUG: http://localhost:5000 "POST /graphql HTTP/1.1" 200 380
DEBUG: Response <RestApiResponse [200]>
DEBUG: Prepared product: modelMain
DEBUG: http://localhost:5000 "POST /graphql HTTP/1.1" 200 105
DEBUG: Response <RestApiResponse [200]>
DEBUG: Source: {root[work]}/Ayon_Tests/maya/props/chairA/work/modeling/ATS_chairA_modeling_v020.ma
DEBUG: Creating new version ...
DEBUG: Prepared version: v015
DEBUG: http://localhost:5000 "POST /graphql HTTP/1.1" 200 112
DEBUG: Response <RestApiResponse [200]>
DEBUG: Anatomy template name: publish
CRITICAL: Error when registering
Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 219, in process
    self.register(instance, file_transactions, filtered_repres)
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 308, in register
    prepared = self.prepare_representation(
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 670, in prepare_representation
    template = os.path.normpath(path_template_obj)
  File "C:\Program Files/Autodesk/Maya2024\Python\lib\ntpath.py", line 491, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not AnatomyStringTemplate

Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2402141620_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 232, in process
    six.reraise(*sys.exc_info())
  File "C:\Program Files\Ynput\AYON 1.0.1\dependencies\six.py", line 719, in reraise
    raise value
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 219, in process
    self.register(instance, file_transactions, filtered_repres)
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 308, in register
    prepared = self.prepare_representation(
  File "C:\Work\REPO\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 670, in prepare_representation
    template = os.path.normpath(path_template_obj)
  File "C:\Program Files/Autodesk/Maya2024\Python\lib\ntpath.py", line 491, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not AnatomyStringTemplate
```

**Review by tokejepsen — DISMISSED** [review]
>  Rename "folder" key to "directory" to match project entity model, but both are compatible for now. 

Does not seem like `folder` is compatible?

```python
from ayon_core.pipeline import Anatomy


project_name = "demo_Commercial"
template_key = "work"
anatomy = Anatomy(project_name)
template_info = anatomy.templates_obj[template_key]
directory_template = template_info["folder"]
```
```
# Error: KeyError: file C:\Users\tokejepsen\ayon-core\client\ayon_core\pipeline\anatomy\templates.py line 329: 'folder'
```

**Comment by iLLiCiTiT** [comment]
> Does not seem like folder is compatible?

You hav eto use both category and template name.

```python
project_name = "demo_Commercial"
category_name = "work"
template_name = "work"
anatomy = Anatomy(project_name)
template_info = anatomy.templates_obj[category_name][template_name]
directory_template = template_info["directory"]
```

**Review by tokejepsen — CHANGES_REQUESTED** [review]
Seems to be an issue when publishing;
```
# Traceback (most recent call last):
#   File "C:\Users\tokejepsen\ayon-launcher\.venv\lib\site-packages\ayon_api\server_api.py", line 6542, in send_batch_operations
#     json.dumps(operation, default=entity_data_json_default)
#   File "C:\Program Files\Autodesk\Maya2023\Python\lib\json\__init__.py", line 234, in dumps
#     return cls(
#   File "C:\Program Files\Autodesk\Maya2023\Python\lib\json\encoder.py", line 199, in encode
#     chunks = self.iterencode(o, _one_shot=True)
#   File "C:\Program Files\Autodesk\Maya2023\Python\lib\json\encoder.py", line 257, in iterencode
#     return _iterencode(o, 0)
#   File "C:\Users\tokejepsen\ayon-launcher\.venv\lib\site-packages\ayon_api\utils.py", line 156, in entity_data_json_default
#     raise TypeError(
# TypeError: Object of type <class 'ayon_core.pipeline.anatomy.templates.AnatomyStringTemplate'> is not JSON serializable
```

**Comment by iLLiCiTiT** [comment]
> Seems to be an issue when publishing;

Should be fixed.

**Review by LiborBatek — APPROVED** [review]
I did ```publish``` with old style template naming and also produced assets via template missing that ```publish_``` prefix and all seems fine and working smoothly.

Been tested in ```maya 2024``` and ```blender``` hosts.

**Pull request merged**
