### PR TITLE
Maya: Account for no placeholder set.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
When building a template from the current scene with `Load template`, the below error would occur.

```
# ==============================
# No object matches name: PLACEHOLDERS_SET
# ==============================
# Traceback (most recent call last):
#   File "C:\Users\tokejepsen\ayon-core\client\ayon_core\pipeline\workfile\workfile_template_builder.py", line 722, in populate_scene_placeholders
#     placeholder_plugin.populate_placeholder(placeholder)
#   File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\maya\api\workfile_template_builder.py", line 246, in populate_placeholder
#     self.populate_load_placeholder(placeholder)
#   File "C:\Users\tokejepsen\ayon-core\client\ayon_core\pipeline\workfile\workfile_template_builder.py", line 1639, in populate_load_placeholder
#     self.post_placeholder_process(placeholder, failed)
#   File "C:\Users\tokejepsen\ayon-core\client\ayon_core\hosts\maya\api\workfile_template_builder.py", line 266, in post_placeholder_process
#     cmds.sets(node, addElement=PLACEHOLDER_SET)
TypeError: No object matches name: PLACEHOLDERS_SET
```

## Testing notes:
1. Open new scene in Maya.
2. Using Loader on a `workfile` or `mayaScene`, prepped as a template, using `Load as template`.

### CODE REVIEW

**Comment by LiborBatek** [comment]
@BigRoy to me its seems like just one unneccessary limitation was removed...I guess you could use just a template file containing loaded assets not any placeholders at all for example?

**Review by LiborBatek — APPROVED** [review]
LGTM, I dont experience any kind of errors regarding non existent ```placeholder set```.

image

I guess its good to go...

**Comment by BigRoy** [comment]
> I guess you could use just a template file containing loaded assets not any placeholders at all for example?

Well, that would be odd - no? Since if it has no placeholders, then there's nothing to run in the workfile template system?

**Comment by tokejepsen** [comment]
> Well, that would be odd - no? Since if it has no placeholders, then there's nothing to run in the workfile template system?

I get this when having a blank Maya scene and use the "Load as template" action.

**Comment by BigRoy** [comment]
> I get this when having a blank Maya scene and use the "Load as template" action.

I guess you're building it from a scene that should've contained the placeholder SET to begin with but it didn't?
Again, I technically don't know why the set was required to begin with so I'm not too bother by the change. Just wonder whether there originally was reason for it to be required :D

**Review by BigRoy — APPROVED** [review]
Looks fine to me.

**Comment by LiborBatek** [comment]
just did one more test with practically empty ```template file``` and all good...it behaves predictably and also gives warning msg if no placeholders found

```# *** WRN: >>> { <ayon_core.hosts.maya.api.workfile_template_builder.MayaTemplateBuilder object at 0x000001CA288A7160> }: [ No placeholders were found. ] 
```

**Review by BigRoy — APPROVED** [review]

**Review by LiborBatek — APPROVED** [review]
I did tested and works ok.

**Review by antirotor — APPROVED** [review]

**Pull request merged**
