### PR TITLE
Fusion: Add instance in context validator

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

For Fusion add instance in context validator like in Maya

## Additional info

Also bug fixes that the task on the instance's was always forced to be the task of the context

## Testing notes:

1. Publish to another folder or task
2. Validation should show error
3. Also has a "Select tool" action that should select the saver

### CODE REVIEW

**Comment by EmberLightVFX** [comment]
THANK YOU SO MUCH FOR THIS!!! I have accidentally published to the wrong asset so many times!
I often copy the content of a master-comp and then replace the asset to the correct one but sometimes when I need to render/publish one at a time forget.

I will absolutely check this out tomorrow!

**Comment by BigRoy** [comment]
It's good to be aware that if you say have multiple comps open that the running Python session is only aware of a single context (that is the folder name shown in the AYON menu) - that is the context that will be validated against.

As such, it _may_ be that this validator gives you more trouble then its worth, because say quickly opening three comps - then going one by one through each one to publish would mean the context validation is wrong for two of them. However, then at the same time; that would actually have meant the context for that publish would've been wrong anyway which would mean that e.g. workfile publish would also go to wrong folder, etc.

Anyway, not a huge issue - but definitely something to be wary of in Fusion.

**Comment by EmberLightVFX** [comment]
I tried it out but I'm getting this error when I'm trying to repair the problem:

```
Action: RepairAction (2925b6dd-0321-4f2d-b210-d2fde08acb8b)

Error: Action failed.

Traceback (most recent call last):
  File "C:\Users\jacob\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403261321_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\jacob\Syncthing\Projekt\Ayon\ayon-core\client\ayon_core\pipeline\publish\publish_plugins.py", line 244, in process
    plugin.repair(instance)
  File "C:\Users\jacob\Syncthing\Projekt\Ayon\ayon-core\client\ayon_core\hosts\fusion\plugins\publish\validate_instance_in_context.py", line 67, in repair
    raise RuntimeError(
RuntimeError: No CreatedInstances found with id 'None in OrderedDict([('renderCompositingMain', <ayon_core.pipeline.create.context.CreatedInstance object at 0x000000000FADAD30>), ('renderCompositingBG', <ayon_core.pipeline.create.context.CreatedInstance object at 0x000000000FADA580>), ('30c8e24f-42fa-4f89-9f7b-5622f322743d', <ayon_core.pipeline.create.context.CreatedInstance object at 0x000000000FADAD00>)])

```

**Comment by BigRoy** [comment]
> tried it out but I'm getting this error when I'm trying to repair the problem:

Thanks - it's because the publishing logic secretly 'swaps out' the instance with a new replaced instance in the `AbstractCollectRender` logic. I have a fix somewhere - let me check.

**Comment by BigRoy** [comment]
@EmberLightVFX could you try again with https://github.com/ynput/ayon-core/pull/217/commits/4c51f3a560109fa75c50f4104e609f93b4c8f28b

It's not the nicest fix. But I don't know another way to get around this "switcheroo" of instances. Maybe @iLLiCiTiT has a better idea.

**Comment by EmberLightVFX** [comment]
Now it works as expected and have already saved me ones 😄 
Everything LGTM if the switcheroo code is accepted by Ynput :)

**Comment by EmberLightVFX** [comment]
@jakubjezek001 Just want to say that I have ran this PR for a week straight now and it works perfectly. Ready to be merged if you ask me!

**Comment by BigRoy** [comment]
After a conversation with @iLLiCiTiT I'll spend some time separating the instance id fix into a PR of its own since it's an odd fix - but also points to a bigger source of issue that expands beyond the scope of just fusion and this PR.

**Comment by BigRoy** [comment]
> After a conversation with @iLLiCiTiT I'll spend some time separating the instance id fix into a PR of its own since it's an odd fix - but also points to a bigger source of issue that expands beyond the scope of just fusion and this PR.
> 
> As such, I've marked this PR draft for now.

The instance id issue is now fixed via PR #405 and thus the workaround is removed from this PR. Please test again! :)

@EmberLightVFX @jakubjezek001

**Review by iLLiCiTiT — APPROVED** [review]
Cannot test it but code changes make sense.

**Comment by BigRoy** [comment]
@EmberLightVFX @jakubjezek001 just pinging again - could any of you take this through a test run?

**Review by jakubjezek001 — APPROVED** [review]
This is looking good and works as expected. Thanks!

**Pull request merged**
