### PR TITLE
Fix: Not removing absolute path in Maya DL submission

### PR DESCRIPTION
**Pull request by kalisp**
## Changelog Description
This occured only in Maya (or DCC with AOV), caused pasting whole absolute path to metadata.json which could cause `Given file names contain full paths` (if ValidateExpectedFiles was disabled). 'files' is expecting only file names, not full paths.

## Testing notes:
1. disable `ValidateExpectedFiles`
2. publish from Maya
3. check metadata.json, shouldn't contain absolute paths, but only file names in `files`

### CODE REVIEW

**Comment by BigRoy** [comment]
This also influences other DCCs and should also need confirmation that it works from other hosts, like Houdini and potentially others that submit to the farm?

Technically it's by [all of these](https://github.com/ynput/ayon-deadline/blob/f747671128e8da1e3553f3b09cc696a77c2172fe/client/ayon_deadline/plugins/publish/global/submit_publish_job.py#L87-L97). So we may want to confirm at least a few:

- [ ] Blender
- [ ] Celaction
- [ ] Fusion
- [ ] Harmony
- [ ] Houdini
- [ ] Max
- [ ] Maya
- [ ] Nuke
- [ ] Unreal

**Review by antirotor — APPROVED** [review]

**Comment by antirotor** [comment]
> This also influences other DCCs and should also need confirmation that it works from other hosts, like Houdini and potentially others that submit to the farm?

We should test it, but on the other hand it is returning back the code that was there before and was removed by mistake (mine ☝🏻 )

**Comment by kalisp** [comment]
> This also influences other DCCs and should also need confirmation that it works from other hosts, like Houdini and potentially others that submit to the farm?
> 
> Technically it's by [all of these](https://github.com/ynput/ayon-deadline/blob/f747671128e8da1e3553f3b09cc696a77c2172fe/client/ayon_deadline/plugins/publish/global/submit_publish_job.py#L87-L97). So we may want to confirm at least a few:
> 
> * [ ]  Blender
> * [ ]  Celaction
> * [ ]  Fusion
> * [ ]  Harmony
> * [ ]  Houdini
> * [ ]  Max
> * [ ]  Maya
> * [x]  Nuke
> * [ ]  Unreal
> 
> We should also confirm the publish jobs work.

It would be affecting only DCCs which have AOVs, which are not these on the list, imho.

**Review by BigRoy — APPROVED** [review]
Didn't test but this is basically the logic that it should be, yes.

**Review by LiborBatek — APPROVED** [review]
I have made full test round with proper rendering via DL and all good...enclosing also JSON scrnshot that no full paths got in (when ```Validate expected files``` been ```OFF``` )

Screenshot 2024-09-23 155914

**Comment by LiborBatek** [comment]
Also works in ```blender``` host . Again full testing with rendering and publish job done. LGTM

**Comment by LiborBatek** [comment]
so now also ```3dsmax``` been tested and all good too

**Pull request merged**
