### PR TITLE
Push to Project: Fix task lowering

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Lower task name when is used, and not when it can be `None`.

## Additional information
Quick fix without knowing full context -> missing test notes @MustafaJafar fill if you can.

### CODE REVIEW

**Review by MustafaJafar — COMMENTED** [review]
when pushing different product types it works as expected. 
Animation_64

when pushing work files I get an error.
Animation_65

Error:
image

**Comment by iLLiCiTiT** [comment]
> Error:

That's something I can't fix as your settings of workfile product name template require task.

**Comment by MustafaJafar** [comment]
> That's something I can't fix as your settings of workfile product name template require task.

Oh, thanks! 
The **default** workfile product name profile includes the task name. And, the error has gone when `{Task[name]}` is removed.
```
ayon+settings://core/tools/creator/product_name_profiles
```

**Review by MustafaJafar — APPROVED** [review]
It works on my side,
However, I had to tweak the default settings to push the workfile to the library project.
```
ayon+settings://core/tools/creator/product_name_profiles
```
Removed `{Task[name]}` 
image

**Pull request merged**
