### PR TITLE
Hiero: colorspace settings aligned with nuke - AY-978

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
Port of https://github.com/ynput/OpenPype/pull/6249

Additional:
- code cosmetics.
- Nuke: remove print statements from nuke startup to reduce the clutter.
- Hiero: bug fix for tags creation, `taskType` > `taskTypes`
- Nuke: added option for setting `Output Transform` for viewer nodes.

## Testing notes:
1. Reset color management settings for Global, Nuke and Hiero.
2. Enable Global color management; `project_settings/global/imageio/activate_global_color_management`
3. Launch Nuke and Hiero.
4. Verify the colorspaces are setup correctly.

### CODE REVIEW

**Comment by moonyuet** [comment]
@tokejepsen would you mind to resolve the conflict?

**Comment by tokejepsen** [comment]
@moonyuet sure, done.

**Review by moonyuet — APPROVED** [review]
The colospace config is set correctly as expected in Nuke and Hiero

**Comment by iLLiCiTiT** [comment]
It's already merged, but it is not backwards compatible...

**Comment by moonyuet** [comment]
> It's already merged, but it is not backwards compatible... Using older addon with settings will break the code.

I wasn't aware of that, (sorry my bad!). I will restore the branch so that @tokejepsen can use the same branch and continue to work on the backwards compatiblity.

**Comment by tokejepsen** [comment]
> It's already merged, but it is not backwards compatible... Using older addon with settings will break the code.

@iLLiCiTiT could you elaborate on this?

**Pull request merged**
