### PR TITLE
TrayPublisher: Move client code

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Moved TrayPublisher addon logic next to server codebase. This is one more step towards splitting addons to their repos.

## Additional info
From now on TrayPublisher addon lives out of ayon-core codebase. Moved client code from hosts, UI from tools and publish plugins with only `"traypublisher"` filtering.

## Testing notes:
1. Create traypublisher package (`python ./server_addons/create_ayon_addons.py --addon traypublisher`).
2. Create core package too.
3. Upload both packages to server.
4. Use boths addon in bundle.
5. Run AYON launcher.
6. Start TrayPublisher tool.
7. Create > publish > validate all works.

### CODE REVIEW

**Comment by MilaKudr** [comment]
```Package creation finished. Output directory: C:\Users\Mila\Code\ayon-core\server_addon\packages
PS C:\Users\Mila\code\ayon-core\server_addon> cd 'C:\Program Files\Ynput\'
PS C:\Program Files\Ynput> cd '.\AYON 1.0.2\'
PS C:\Program Files\Ynput\AYON 1.0.2> .\ayon_console.exe addon traypublisher launch
>>> Connected to AYON server http://localhost:5000
*** AYON [1.0.2] ---------------------------------------------------------------------------------------------------------------------------------------------------------------
>>> Using AYON from [ C:\Program Files\Ynput\AYON 1.0.2 ]
... AYON variant: [ production ]
... AYON bundle:  [ 2024.05.0-full-2024-05-25-v3 ]
>>> loading environments ...
  - global AYON ...
  - for addons ...
!!! AYON crashed:
Traceback (most recent call last):
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\addons\core_0.3.3-dev.1\ayon_core\cli.py", line 287, in main
    main_cli(obj={}, prog_name="ayon")
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\dependency_packages\ayon_2403071252_windows.zip\dependencies\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\addons\traypublisher_0.2.0\ayon_traypublisher\addon.py", line 58, in launch
    from ayon_traypublisher import ui
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\addons\traypublisher_0.2.0\ayon_traypublisher\ui\__init__.py", line 1, in <module>
    from .window import main
  File "C:\Users\Mila\AppData\Local\Ynput\AYON\addons\traypublisher_0.2.0\ayon_traypublisher\ui\window.py", line 16, in <module>
    from ayon_core.hosts.traypublisher.api import TrayPublisherHost
  File "C:\Program Files\Ynput\AYON 1.0.2\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ayon_core.hosts.traypublisher'
```

**Comment by iLLiCiTiT** [comment]
Please try again.

**Review by 64qam — APPROVED** [review]
all good

**Comment by MilaKudr** [comment]
This PR works in my environment.

**Pull request merged**
