### PR TITLE
Nuke: Support options for reading deep exr in load clips

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
This PR is to add the support of reading deep exr in load clips. Users can choose to turn on/off of reading the deep exr node. By default is False.

## Additional info
Make sure you have built the latest nuke addon for this support.

## Testing notes:
1. Go to `ayon+settings://nuke/load/LoadClip/options_defaults/deep_exr` to turn on the toggle
2. Or you can choose the options through  `AYON->Load...` after launching Nuke
image
image
3. Load the clips
4. The deep read node should be used for loading clip while the deep exr option turns on. The read node should be used when the option turns off.

### CODE REVIEW

**Review by jakubjezek001 — APPROVED** [review]
approved by mistake

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
Issue is that `colorspace` knob DeepLoader class doesn't exists. 
image

```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\CODE\__PYPE\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\plugins\load\load_clip.py", line 192, in load
    self.set_colorspace_to_node(
  File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\plugins\load\load_clip.py", line 418, in set_colorspace_to_node
    and colorspace_exists_on_node(read_node, used_colorspace)
  File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\api\utils.py", line 110, in colorspace_exists_on_node
    colorspace_knob = node['colorspace']
NameError: knob colorspace does not exist
```

**Comment by moonyuet** [comment]
> Issue is that `colorspace` knob DeepLoader class doesn't exists. image
> 
> ```
> Traceback (most recent call last):
>   File "C:\CODE\__PYPE\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
>     load_with_repre_context(
>   File "C:\CODE\__PYPE\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
>     return loader.load(repre_context, name, namespace, options)
>   File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\plugins\load\load_clip.py", line 192, in load
>     self.set_colorspace_to_node(
>   File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\plugins\load\load_clip.py", line 418, in set_colorspace_to_node
>     and colorspace_exists_on_node(read_node, used_colorspace)
>   File "C:\CODE\__PYPE\ayon-core\client\ayon_core\hosts\nuke\api\utils.py", line 110, in colorspace_exists_on_node
>     colorspace_knob = node['colorspace']
> NameError: knob colorspace does not exist
> ```

Fixed. Can you please test again? Thanks!

**Review by jakubjezek001 — APPROVED** [review]
all works fine now, thanks! ;)

**Pull request merged**
