### PR TITLE
Moved some dependencies to runtime dependencies

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Move some dependencies to runtime depedencies. Similar changes to https://github.com/ynput/OpenPype/pull/6155 in OpenPype.

## Additional info
Click has replacement with `click_wrap` for addons. And other moved dependencies are used only in ayon-launcher process. This change may affect other addons which are not yet using `click_wrap`.

## Testing notes:
This change requires new dependency packages.
1. Upload package to server.
2. Create dependency packages.
3. All moved dependencies should be in runtimeDependencies and should not affect existing code.

### CODE REVIEW

**Comment by tokejepsen** [comment]
> All moved dependencies should be in runtimeDependencies and should not affect existing code.

How do we verify this?

**Comment by iLLiCiTiT** [comment]
> How do we verify this?

Well, it's complex case, one example is that if you launch a DCC and run `import click` it should crash with `ImportError` because is not available or import it ok, but the click should not be taken from ayon dependency package.

**Comment by tokejepsen** [comment]
> Well, it's complex case, one example is that if you launch a DCC and run import click it should crash with ImportError because is not available or import it ok, but the click should not be taken from ayon dependency package.

So launch host and import the modules that are moved to the runtime dependencies, print and see where they are coming from? Should not be coming from the dependency package.

**Comment by iLLiCiTiT** [comment]
> So launch host and import the modules that are moved to the runtime dependencies, print and see where they are coming from? Should not be coming from the dependency package.

Exactly, they should not be comming from dependency package in DCCs, but should be available in ayon launcher process.

**Comment by tokejepsen** [comment]
Ran this in Nuke:
```python
import importlib


module_names = [
    "aiohttp_json_rpc",
    "aiohttp_middlewares",
    "wsrpc_aiohttp",
    "click",
    "pynput",
]
for module_name in module_names:
    module = importlib.import_module(module_name)
    print(module)
```
Results:
```
<module 'aiohttp_json_rpc' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402261802_windows.zip\\dependencies\\aiohttp_json_rpc\\__init__.py'>
<module 'aiohttp_middlewares' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402261802_windows.zip\\dependencies\\aiohttp_middlewares\\__init__.py'>
<module 'wsrpc_aiohttp' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402261802_windows.zip\\dependencies\\wsrpc_aiohttp\\__init__.py'>
<module 'click' from 'C:\\Users\\tokejepsen\\ayon-launcher\\.venv\\lib\\site-packages\\click\\__init__.py'>
<module 'pynput' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402261802_windows.zip\\dependencies\\pynput\\__init__.py'>
```
Seems like all the modules are still coming from the dependency package.

**Comment by iLLiCiTiT** [comment]
> Seems like all the modules, except click, are still coming from the dependency package.

Looks like you have old ayon launcher, or you have `.venv` and `vendor` from older version of launcher, and the dependency package was not created for this branch of ayon-core.

**Comment by tokejepsen** [comment]
> Looks like you have old ayon launcher, or you have .venv and vendor from older version of launcher, and the dependency package was not created for this branch of ayon-core.

These are the steps I've done now;

- cleared `.venv` and `vendor` from ayon-launcher.
- built and uploaded ayon-launcher.
- created and uploaded ayon-core package.
- created new production bundle with latest ayon-launcher and ayon-core.
- created new dependency package with ayon-dependencies-tool.
- ran Nuke and executed the below:

```
import importlib


module_names = [
    "aiohttp_json_rpc",
    "aiohttp_middlewares",
    "wsrpc_aiohttp",
    "click",
    "pynput",
]
for module_name in module_names:
    module = importlib.import_module(module_name)
    print(module)
```
Results
```
<module 'aiohttp_json_rpc' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402272059_windows.zip\\dependencies\\aiohttp_json_rpc\\__init__.py'>
<module 'aiohttp_middlewares' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402272059_windows.zip\\dependencies\\aiohttp_middlewares\\__init__.py'>
<module 'wsrpc_aiohttp' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402272059_windows.zip\\dependencies\\wsrpc_aiohttp\\__init__.py'>
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Program Files\Nuke15.0v2\python310.zip\importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'click'
```
The missing `click` module is expected?
The other modules are still coming from the dependency package though.

**Comment by iLLiCiTiT** [comment]
> The missing click module is expected?

Yes.

> The other modules are still coming from the dependency package though.

That should not happen. Is there a chance that you had openpype addon enabled in the bundle too?

**Comment by tokejepsen** [comment]
> That should not happen. Is there a chance that you had openpype addon enabled in the bundle too?

Good shout! Still a couple of modules in the dependency package.

```
import importlib


module_names = [
    "aiohttp_json_rpc",
    "aiohttp_middlewares",
    "wsrpc_aiohttp",
    "click"
    "pynput",
]
for module_name in module_names:
    try:
        module = importlib.import_module(module_name)
        print(module)
    except ModuleNotFoundError:
        print("{} not found".format(module_name))
# Result: aiohttp_json_rpc not found
<module 'aiohttp_middlewares' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402281332_windows.zip\\dependencies\\aiohttp_middlewares\\__init__.py'>
<module 'wsrpc_aiohttp' from 'C:\\Users\\tokejepsen\\AppData\\Local\\Ynput\\AYON\\dependency_packages\\ayon_2402281332_windows.zip\\dependencies\\wsrpc_aiohttp\\__init__.py'>
clickpynput not found
```

**Review by tokejepsen — CHANGES_REQUESTED** [review]
Still some dependencies unresolved; https://github.com/ynput/ayon-core/pull/65#issuecomment-1969012976

**Comment by iLLiCiTiT** [comment]
> Still some dependencies unresolved; https://github.com/ynput/ayon-core/pull/65#issuecomment-1969012976

I don't think correct dependency package was used. It took the dependencies from `dependencies` folder, but they should be located in `runtime` (if the dependency package would be created with the ayon-core).

**Pull request merged**
