### PR TITLE
Houdini: Add generic filepath loader

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Add generic filepath loader that can be loaded and managed via AYON.

## Additional info

This is useful if for a particular workflow there is no existing loader yet. A Houdini artists can load as the generic filepath loader and then reference the relevant Houdini parm to use the exact value. The benefit is that this filepath will be managed and can be updated as usual.

## Testing notes:

Each of the below should work:

1. Load some paths via loader
2. Update / switch folders via scene inventory (manage)
3. Remove via scene inventory  (manage)

### CODE REVIEW

**Comment by BigRoy** [comment]
> I think Houdini addon version should be bumped to indicate the change.

@iLLiCiTiT @antirotor thoughts on this? Should I bump the Houdini server addon version?

**Comment by iLLiCiTiT** [comment]
> Should I bump the Houdini server addon version?

Server version bump at this moment makes sense only if you change server code (only settings at this moment).

**Comment by MustafaJafar** [comment]
> Server version bump at this moment makes sense only if you change server code (only settings at this moment). 

Fair!

**Comment by BigRoy** [comment]
> > Should I bump the Houdini server addon version?
> 
> Server version bump at this moment makes sense only if you change server code (only settings at this moment). The code change is in ayon-core and change of server addon version has no effect.

In that case, all should be good as is.

**Pull request merged**
