### PR TITLE
Loader: Products model fetches versions information once

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Get version related information once for all products instead of per item.

## Additional info
This is a draft that was not tested, but should enhance speed of the UI.

## Testing notes:
1. Compare speed of Loader before and after this PR.
2. Validate that it actually shows correct information, especially when sitesync is enabled.

### CODE REVIEW

**Comment by kalisp** [comment]
Honestly I don't notice a difference (on my localhost, on largest project) and I cannot use dev bundle on ayon.dev (investigating).

**Comment by BigRoy** [comment]
> Honestly I don't notice a difference (on my localhost, on largest project) and I cannot use dev bundle on ayon.dev (investigating).

For what it's worth - it's not about the amount of folders in a project - but have say 40 products in one folder (with each having 10+ versions.). I think it's not as much about the amount of versions but mostly about the amount of products.

Note that I have site sync disabled (and the site sync addon is _not_ installed). I have no idea whether that could technically influence the duration of the query being made to the database? Maybe it fails to collect some data for publishes made without site sync or alike and thus may be slower to respond?

I still need to test whether this PR really makes any difference though.

**Comment by iLLiCiTiT** [comment]
> I still need to test whether this PR really makes any difference though.

I would say this is the important question.

**Review by BigRoy — APPROVED** [review]
Good to note that I tested **without site sync**. I do not have the addon installed nor enabled.

---

So, with this PR performance for the loader on a cold refresh is much much better. 

A single refresh now just logs:
```
Resetting dropped connection: localhost
http://localhost:5000 "POST /graphql HTTP/1.1" 200 226
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
Executing [GET] projects/ayontest/hierarchy
http://localhost:5000 "GET /api/projects/ayontest/hierarchy HTTP/1.1" 200 6039
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 4527
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 542
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 141622
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 2526
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
```
Which is a remainder of 9 queries?

Without this PR a refresh turns out to:
```
Resetting dropped connection: localhost
http://localhost:5000 "POST /graphql HTTP/1.1" 200 226
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
Executing [GET] projects/ayontest/hierarchy
http://localhost:5000 "GET /api/projects/ayontest/hierarchy HTTP/1.1" 200 6039
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 4527
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 542
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 141622
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 378
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 244
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 378
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 243
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 244
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 246
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 112
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 245
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 250
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 379
Response <RestApiResponse [200]>
http://localhost:5000 "POST /graphql HTTP/1.1" 200 155
Response <RestApiResponse [200]>
```
Which is a whopping 39 responses.

Both were for this folder:
image

It also refreshes much faster - I didn't time it, but definitely down from over a couple of seconds to less than a second.

**Pull request merged**
