### PR TITLE
Unreal: decouple UIs to separate process

### PR DESCRIPTION
**Pull request by simonebarbieri**
## Brief description
Run unreal commands from OP through websocket communication.

## Description
UE has the ability to have its python to be called remotely. This PR allow us to run all UIs as separete processes that are comunicating with UE. We'll no longer need to install PySide2 to Unreal.

PR linked to https://github.com/ynput/OpenPype/pull/4075

### Publishing

- [ ] Camera
- [ ] Layout
- ⛔ Level (see https://github.com/ynput/ayon-core/pull/111#issuecomment-2152273399)
- [ ] Look
- [ ] Render
	- [ ] Local
	- [ ] Farm
- [ ] Static Mesh FBX
- [ ] UAsset

### Loading

- ⛔ Animation (alembic)
- [ ] Animation (FBX)
- ⛔ Camera (FBX)
- ⛔ Pointcache (alembic)
- ⛔ Layout (json)
- [ ] Layout from existing
- [ ] Skeletal Mesh (alembic)
- [ ] Skeletal Mesh (FBX)
- ⛔ Static Mesh (alembic)
- [ ] Static Mesh (FBX)
- [ ] Load UAsset
- ⛔ Load Yeti Cache

### CODE REVIEW

**Comment by moonyuet** [comment]
I have tested with the code and there is still the openpype-related code which hasn't been converted. e.g. the hook-related script below.
https://github.com/ynput/ayon-core/blob/8d806ddc4ffa50c1435a8447eff9ff244c1d6e67/client/ayon_core/hosts/unreal/hooks/pre_workfile_preparation.py#L16

**Comment by antirotor** [comment]
Some errors coming from UE5.4:

## Loaders
Some loader plugins fail on discovery:

- `load_camera`
- `load_layout`
- `load_yeticache`

<details>
<summary>Server log</summary>
<pre>
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_camera.py"
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_camera.py", line 7, in <module>
    from ayon_core.client import get_assets, get_asset_by_name
ImportError: cannot import name 'get_assets' from 'ayon_core.client' (unknown location)
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_layout.py"
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_layout.py", line 7, in <module>
    from ayon_core.client import get_assets, get_asset_by_name
ImportError: cannot import name 'get_assets' from 'ayon_core.client' (unknown location)
WARNING:ayon_core.lib.python_module_tools:Failed to load path: "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_yeticache.py"
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_yeticache.py", line 12, in <module>
    import unreal  # noqa
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-launcher\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'unreal'
>>> [ *** Failed to load 3 files
- C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_camera.py
**********
Traceback (most recent call last):

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_camera.py", line 7, in <module>
    from ayon_core.client import get_assets, get_asset_by_name

ImportError: cannot import name 'get_assets' from 'ayon_core.client' (unknown location)

**********
- C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_layout.py
**********
Traceback (most recent call last):

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_layout.py", line 7, in <module>
    from ayon_core.client import get_assets, get_asset_by_name

ImportError: cannot import name 'get_assets' from 'ayon_core.client' (unknown location)

**********
- C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_yeticache.py
**********
Traceback (most recent call last):

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_yeticache.py", line 12, in <module>
    import unreal  # noqa

  File "C:\Users\annat\Documents\Projects\Ayon\ayon-launcher\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

ModuleNotFoundError: No module named 'unreal'

********** ]
</pre>
</details>

### Load Alembic PointCache (abc)
 Crashing on load both with `load_staticmesh_abc` and `load_geometrycache_abc` with the same error:

```
During load error happened on Product: "modelMain" Representation: "abc" Version: 16

Error message: '_id'

Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_geometrycache_abc.py", line 121, in load
    "representation": str(context["representation"]["_id"]),
KeyError: '_id'
```

### Import FBX Skeletal Mesh (fbx)
Crashing on load:

```
During load error happened on Product: "rigMain" Representation: "fbx" Version: 3

Error message: 'NoneType' object has no attribute 'get'

Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_skeletalmesh_fbx.py", line 86, in load
    asset = context.get('asset').get('name')
AttributeError: 'NoneType' object has no attribute 'get'
```

### Import Alembic Animation (abc)
During the load it produces:

```
During load error happened on Product: "animationAlice_rigMain_01_" Representation: "abc" Version: 4

Error message: Error happened: {'code': -32000, 'message': 'Python Execution in Unreal Failed!', 'data': ''}

Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_alembic_animation.py", line 90, in load
    self._import_abc_task(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\load\load_alembic_animation.py", line 49, in _import_abc_task
    send_request("import_abc_task", params=params)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\api\pipeline.py", line 166, in send_request
    communicator.send_request(request, params)
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\api\communication_server.py", line 605, in send_request
    return self.websocket_rpc.send_request(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\api\communication_server.py", line 291, in send_request
    raise Exception("Error happened: {}".format(error))
Exception: Error happened: {'code': -32000, 'message': 'Python Execution in Unreal Failed!', 'data': ''}
```
Without relevant server log. When **run again** it will load correctly. But after that, Loader stops working with this server log:

<details>
<summary>Server Log</summary>
<pre>
INFO:ayon_core.hosts.unreal.api.communication_server:Triggering Loader tool
DEBUG:ayon_core.hosts.unreal.api.communication_server:Executing process in main thread
INFO:ayon_core.hosts.unreal.api.communication_server:Running callback: <bound method HostToolsHelper.show_loader of <openpype.tools.utils.host_tools.HostToolsHelper object at 0x0000012ECC4F7700>>
Using existing QApplication..
DEBUG:ayon_core.hosts.unreal.api.communication_server:Sending request to client localhost:62030 (ls, {}) id: 12
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\ui\window.py", line 513, in _on_folders_refresh
    self._products_widget.refresh()
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\ui\products_widget.py", line 232, in refresh
    self._refresh_model()
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\ui\products_widget.py", line 274, in _refresh_model
    self._products_model.refresh(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\ui\products_model.py", line 429, in refresh
    product_items = self._controller.get_product_items(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\control.py", line 192, in get_product_items
    return self._products_model.get_product_items(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\products.py", line 229, in get_product_items
    self._refresh_product_items(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\products.py", line 617, in _refresh_product_items
    product_items_by_id = self._query_product_items_by_ids(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\products.py", line 537, in _query_product_items_by_ids
    return self._create_product_items(
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\models\products.py", line 463, in _create_product_items
    loaded_product_ids = self._controller.get_loaded_product_ids()
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\tools\loader\control.py", line 365, in get_loaded_product_ids
    uuid.UUID(repre_id)
  File "C:\Users\annat\.pyenv\pyenv-win\versions\3.9.13\lib\uuid.py", line 171, in __init__
    raise TypeError('one of the hex, bytes, bytes_le, fields, '
TypeError: one of the hex, bytes, bytes_le, fields, or int arguments must be given
</pre>
</details>

**Comment by antirotor** [comment]
## Publisher plugins crashing:

These plugins are crashing with the same traceback:
- `collect_current_file.py`
- `collect_instance_members.py`
- `collect_render_instances.py`
- `extract_camera.py`
- `extract_layout.py`
- `extract_look.py`
- `extract_uasset.py`
- `validate_no_dependencies.py`

<details>
<summary>Traceback</summary>
<pre>
Filepath:
C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\publish\collect_current_file.py

Traceback:
Traceback (most recent call last):
File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 257, in publish_plugins_discover
module = import_filepath(abspath, mod_name)
File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
module_loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\plugins\publish\collect_current_file.py", line 3, in 
import unreal # noqa
File "C:\Users\annat\Documents\Projects\Ayon\ayon-launcher\vendor\python\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
return original_import(name, *args, **kwargs)
</pre>
</details>

**Comment by antirotor** [comment]
when https://github.com/ynput/ayon-core/pull/614 is merged, we need to reopen it in https://github.com/ynput/ayon-unreal

**Comment by antirotor** [comment]
This is moved https://github.com/ynput/ayon-unreal/pull/2

**Pull request closed without merging**
