### PR TITLE
Unreal: Deadline support with Perforce

### PR DESCRIPTION
**Pull request by kalisp**
## Changelog Description
This PR should add possibility to render Unreal project on Deadline with Perforce integration (and possibly without P4). 

## Additional info
It requires https://github.com/ynput/ayon-version-control/pull/2, working Perforce server with user credentials and P4 workspace created following some P4 depot and stream

## Testing notes:
1. set info about P4
image
2,provide P4 user credentials (in `Project Settings > Site Settings`)
image
3. Deadline must have some environment variables set
 - either via OS environments
 - OR via env vars set on Unreal in `Applications` addon
image
Expected env var: (applicable values for DL WORKER, not artist machine)
```
   "UnrealExecutable": {"windows": "C:/Program Files/Epic Games/UE_5.3/Engine/Binaries/Win64/UnrealEditor-Cmd.exe"},
   "UnrealExecutable_5_3": {"windows": "C:/Program Files/Epic Games/UE_5.3/Engine/Binaries/Win64/UnrealEditor-Cmd.exe"},
   "P4PORT":"localhost:1666",
   "P4USER":"admin",
   "P4PASSWD":"pass"
   ```
4. Copy `ayon_core/modules/deadline/repository/custom/plugins/UnrealEngine5` to `DEADLINE_REPO/custom` folder
5. Render for DL uses existing creator and follow existing workflow, only added `Render target`
image
6. Provide path for render config `ayon+settings://unreal/render_config_path` and make sure that it exists in Unreal project
image
7. There must be at least 2 instances to be published, `publish_commit` creates instance with information about change list
image

### CODE REVIEW

**Comment by antirotor** [comment]
I am having issues opening `Sync tool` in Unreal:
<details>
  <summary>Traceback from Unreal Log</summary>
<pre>
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\api\tools_ui.py", line 113, in _on_tool_require
LogPython: Error:     show_changes(self)
LogPython: Error:   File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\hosts\unreal\api\tools_ui.py", line 194, in show_changes
LogPython: Error:     from version_control.changes_viewer import ChangesWindows
LogPython: Error:   File "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\Python3\Win64\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
LogPython: Error:     return original_import(name, *args, **kwargs)
LogPython: Error:   File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\version_control_0.0.2\version_control\changes_viewer\__init__.py", line 1, in <module>
LogPython: Error:     from .window import (
LogPython: Error:   File "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\Python3\Win64\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
LogPython: Error:     return original_import(name, *args, **kwargs)
LogPython: Error:   File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\version_control_0.0.2\version_control\changes_viewer\window.py", line 15, in <module>
LogPython: Error:     from .control import ChangesViewerController
LogPython: Error:   File "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\Python3\Win64\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
LogPython: Error:     return original_import(name, *args, **kwargs)
LogPython: Error:   File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\version_control_0.0.2\version_control\changes_viewer\control.py", line 8, in <module>
LogPython: Error:     from ayon_core.tools.ayon_utils.models import HierarchyModel
LogPython: Error: ImportError: cannot import name 'HierarchyModel' from 'ayon_core.tools.ayon_utils.models' (unknown location)
</pre>
</details>

**Comment by kalisp** [comment]
> I am having issues opening `Sync tool` in Unreal:

Fixed in https://github.com/ynput/ayon-version-control/pull/2

**Comment by kalisp** [comment]
It needs new dependency package! P4 was moved to `runtimeDependencies`, eg. it shouldn't get picked up.

**Review by antirotor — CHANGES_REQUESTED** [review]
There are some issues I put together in this PR even though some of it is related to [ayon_version_control](https://github.com/ynput/ayon-version-control) (where I'll create issue)

```
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 92, in modules_from_path
    module = import_filepath(full_path, mod_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
    module_loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\annat\Documents\Projects\Ayon\ayon-version-control\client\version_control\plugins\create\unreal\publish_commit.py", line 4, in <module>
    from ayon_core.client import get_asset_by_name
ImportError: cannot import name 'get_asset_by_name' from 'ayon_core.client' (unknown location)
```
so this is happening because of changes in **ayon_core**.

There is some confusion about Movie Render Queue that needs to be created manually. At one point, it is taking it from the project settings (`ayon+settings://unreal/render_config_path`) but down the line the path is hardcoded and plugin is expecting `/Game/Ayon/renderQueue`)

If I understand it correctly, there is difficulity to create MovieRenderQueue configuration object from Unreal Python API (as stated in comments) but I was successful with following code:

```python
import unreal

config_factory = unreal.MoviePipelinePrimaryConfigFactory()
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
config = asset_tools.create_asset(asset_name="testConfig", package_path="/Game/Ayon", asset_class=unreal.MoviePipelinePrimaryConfig, factory=config_factory)
```

Another topic is inclusion of Unreal5 Deadline plugin in Deadline module - is it the right way? It is full of linter errors so either we need to leave it there but add it to linter ignores.

The last thing :) I understand that the one Perforce workspace per AYON project is the limitation. It is little difficult to test multilpe version of Unreal because project file are commited to workspace and when you switch Unreal version, you need to basically wipe out everything. Just mentioning this as it needs to be clearly stated in documentation.

**Comment by antirotor** [comment]
There are also crashes during the publishing:

<details>
  <summary><strong>collect_latest_changelist.py</strong> traceback</summary>
<pre>
Traceback (most recent call last):
File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 257, in publish_plugins_discover
module = import_filepath(abspath, mod_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\annat\Documents\Projects\Ayon\ayon-core\client\ayon_core\lib\python_module_tools.py", line 38, in import_filepath
module_loader.exec_module(module)
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "C:\Users\annat\Documents\Projects\Ayon\ayon-version-control\client\version_control\plugins\publish\collect_latest_changelist.py", line 14, in 
from version_control.backends.perforce.api.rest_stub import (
File "C:\Users\annat\Documents\Projects\Ayon\ayon-version-control\client\version_control\backends\perforce\api\__init__.py", line 25, in 
import P4
File "C:\Users\annat\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406041254_windows.zip\dependencies\P4.py", line 420, in 
import P4API
ModuleNotFoundError: No module named 'P4API'
```
</pre>

and basically same for `collect_version_control_login`, `integrate_perforce` and `validate_workspace`

**Comment by antirotor** [comment]
when https://github.com/ynput/ayon-core/pull/614 is merged, we need to reopen it in https://github.com/ynput/ayon-unreal

**Comment by kalisp** [comment]
Closing this one in favor https://github.com/ynput/ayon-core/pull/670 which contains new location of code in `server_addons`

**Pull request closed without merging**
