### PR TITLE
Publisher: Use hierarchy model

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Publisher is using `HierarchyModel` to get folders and tasks.

## Additional info
First modification of publisher tool before using AYON entities. Biggest change is that `HierarchyModel` is used to query folders. There were some necessary changes in UI to create wrapper controllers for context selection in create page and asset dialog. Use folder naming in publisher tool. Fixed few found bugs in Hierarchy model and added more public methods to `FoldersWidget` and `TasksWidget`.

## Testing notes:
1. Launch host of your choice. Ideally not traypublisher...
2. Open publisher tool.
3. Page on Create tab should show context and is responsible to folder and task changes.
4. Existing instances should not have any issues with context.
5. Newly created instances should have correct context selected in UI.
6. It is possible to change context of instance in Publish tab.
7. Instance with changed context can be published.

### CODE REVIEW

**Comment by MustafaJafar** [comment]
Tested in Houdini, It works. 
Let me know if I got it correctly.

So in essence, I can change context before creating new instances from here ?
image

And, for existent instances, I can change it as usual from here 
image

---

Also, I met this error.. 
It happens because of the second argument in this line.. this underscore doesn't exist in develop branch.

https://github.com/ynput/ayon-core/blob/7881ba253b78e8a68a3f24fdf1777e66d900be25/client/ayon_core/plugins/publish/collect_comment.py#L45

```
*** WRN: >>> { filter_pyblish_plugins }: [  FAILED to apply settings on plugin CollectInstanceCommentDef  ] 
==============================
apply_settings() missing 1 required positional argument: '_'
==============================
Traceback (most recent call last):
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 450, in filter_pyblish_plugins
    plugin.apply_settings(project_settings)
TypeERROR: apply_settings() missing 1 required positional argument: '_'
```

**Review by MustafaJafar — APPROVED** [review]
Tested in Houdini, It works. 
Let me know if I got it correctly.

So in essence, I can change context before creating new instances from here ?
image

And, for existent instances, I can change it as usual from here 
image

---

Also, I met this error.. 
It happens because of the second argument in this line.. this underscore doesn't exist in develop branch.

https://github.com/ynput/ayon-core/blob/7881ba253b78e8a68a3f24fdf1777e66d900be25/client/ayon_core/plugins/publish/collect_comment.py#L45

```
*** WRN: >>> { filter_pyblish_plugins }: [  FAILED to apply settings on plugin CollectInstanceCommentDef  ] 
==============================
apply_settings() missing 1 required positional argument: '_'
==============================
Traceback (most recent call last):
  File "E:\Ynput\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 450, in filter_pyblish_plugins
    plugin.apply_settings(project_settings)
TypeERROR: apply_settings() missing 1 required positional argument: '_'
```

**Comment by BigRoy** [comment]
> image

Can we fix the madly large "Go to current context" button next to the filter field top left? That was an arrow icon before?

**Comment by iLLiCiTiT** [comment]
> Let me know if I got it correctly.

Exactly.

> It happens because of the second argument in this line.. this underscore doesn't exist in develop branch.

Already fixed in develop.

> Can we fix the madly large "Go to current context" button next to the filter field top left?

Good catch. Forgot about that.

**Comment by MustafaJafar** [comment]
This is how the button looks like on my side.
image

**Comment by BigRoy** [comment]
> This is how the button looks like on my side. image

Not perfect styling wise with the lack of padding/margins but much better already.

**Pull request merged**
