### PR TITLE
Chore/ Add Zbrush as part of the applications existed in the launcher

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
This PR is to prepare for the integration implemented in ayon-zbrush repo https://github.com/ynput/ayon-zbrush

## Additional info
n/a

## Testing notes:
1.  build application addon with this repo
2. build along with the addon built with https://github.com/ynput/ayon-zbrush
3. Launch Zbrush

### CODE REVIEW

**Comment by BigRoy** [comment]
> build along with the addon built with https://github.com/ynput/ayon-zbrush

I assume you're about to move the code of #112 to that repository and close #112 here?

**Comment by moonyuet** [comment]
> > build along with the addon built with https://github.com/ynput/ayon-zbrush
> 
> I assume you're about to move the code of #112 to that repository and close #112 here?

yes it is.

**Review by LiborBatek — COMMENTED** [review]
Does not launch Zbrush for me when triggered by its launch icon...

Any idea?

**Comment by BigRoy** [comment]
> Does not launch Zbrush for me when triggered by its launch icon...
> 
> Any idea?

It might need the standalone `ayon-zbrush` addon to access the "host" correctly for this to work.
Do you see any errors in the console of the launcher?

Or otherwise, maybe your zbrush is not installed at `C:\Program Files\Maxon ZBrush 2024\ZBrush.exe`?
I suspect the issue is the first thing however with the lack of ayon zbrush host.

**Comment by moonyuet** [comment]
> Does not launch Zbrush for me when triggered by its launch icon...
> 
> Any idea?

it can contribute to the recent change of the loaders regarding to the product-type.

**Review by LiborBatek — APPROVED** [review]
After adding the Zbrush addon to my bundle on Ayon, all works and ZB being launched via Ayon Launcher and with ```AYON Tools``` present and working.

I was also able to produce ```model``` via ```Publish``` action. 

image

**Pull request merged**
