### PR TITLE
Add DNG support

### PR DESCRIPTION
**Pull request by EmberLightVFX**
## Changelog Description
This PR adds .dng as an image extension in IMAGE_EXTENSIONS and adds .dng to image, plate and render for the tray publisher.

## Additional info
Maybe some good to know about dng:
DNG (digital negativ) is the standard format used for film-scans and used in as good as all projects that has bin filmed on real film.
By default scans ends up in cineon log with a srgb gamut. It's the same as what RedLogFilm uses.

## Testing notes:
1. Publish a dng image or sequence.
2. Load the dng sequence in Nuke or Fusion

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Didn't test it - but changes look good to me!

**Comment by MustafaJafar** [comment]
I think Tray publisher addon version should be bumped as this PR updates its settings.  
what do you think @iLLiCiTiT  ?

**Comment by iLLiCiTiT** [comment]
> I think Tray publisher addon version should be bumped as this PR updates its settings.

Yes, settings change >>> version bump.

**Comment by EmberLightVFX** [comment]
> Yes, settings change >>> version bump.

Where do I bump the tray-publisher version?

**Comment by EmberLightVFX** [comment]
The linting check failed when I bumped up the version :S no idea why

**Comment by BigRoy** [comment]
> The linting check failed when I bumped up the version :S no idea why

You can ignore that - for now that'll be happening on any commit due to this recent merge https://github.com/ynput/ayon-core/pull/192

Work is being done to resolve that in #196

**Review by BigRoy — APPROVED** [review]
Looks good to me. Maybe up to @antirotor or @jakubjezek001 to look into whatever we need to do with that linter stuff.

**Pull request merged**
