### PR TITLE
Nuke: openpype expose knobs validator - OP-8166

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
Port of https://github.com/ynput/OpenPype/pull/6213

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
I don't think this is needed in ayon-core.

**Comment by tokejepsen** [comment]
> I don't think this is needed in ayon-core. Settings overrides do not work the same way as in OpenPype.

So if an existing production is using ayon now without the `Exposed Knobs` setting, what would happen?

**Comment by iLLiCiTiT** [comment]
> So if an existing production is using ayon now without the Exposed Knobs setting, what would happen?

In AYON you'll always get current settings model values. And if the settings model has the attribute, you'll get the value, in other words core version `1.1.1` will always get settings values compatible with model `1.1.1`.

NOTE: That might not be true in case of addons which have settings in `server_addons`, because client code lives in core and does not have to be in sync on server with settings.

**Comment by tokejepsen** [comment]
> NOTE: That might not be true in case of addons which have settings in server_addons, because client code lives in core and does not have to be in sync on server with settings.

So we do have to merge this PR?
Dont mind whether we do or not, just need a decision. If its a problem, then its a quick and easy fix later.

**Comment by iLLiCiTiT** [comment]
> Dont mind whether we do or not, just need a decision. If its a problem, then its a quick and easy fix later.

Huge sorry, I just realized the change is in nuke and not in core settings. Yes we should merge this.

**Review by iLLiCiTiT — APPROVED** [review]

**Pull request merged**
