### PR TITLE
Photoshop: UI icons

### PR DESCRIPTION
**Pull request by scottmcdonnell**
Add icons to  Adobe Photoshop - Ayon extension.

old Avalon panel:
panel

new Ayon panel:
panel

### CODE REVIEW

**Comment by BigRoy** [comment]
Is there a reason it has less menu entries? Were many obsolete? Are we losing any functionality?

**Comment by scottmcdonnell** [comment]
> Is there a reason it has less menu entries? Were many obsolete? Are we losing any functionality?

That was the Avalon menu structure and it was the screen grab in the repo. Before the icon update the menu had 5 items:

1. Workfiles...
2. Load...
3. Publish...
4. Manage...
5. Experimental Tools...

I dropped Experimental tools as it just opened a message box that there were none :) 

**I think there should be consistent icons, names and order across all DCs.** 
All hosts should be matched to agreed icons, names and order - Maya shelf supports icons, Harmony menu too, Nuke menus support icons to left of text etc.

There is a few personal opinions in this PR:

- I prefer "Inventory" to "Manage" and see it used in several tools. 
- I also prefer nouns for tool names instead of verbs "Load..." => "Loader" since it opens the Loader tool. 
- "Experimental Tools" if required in any DC could be "Tools" with maybe [an ellipsis icon](https://cdn.iconscout.com/icon/premium/png-512-thumb/ellipsis-1-228371.png?f=webp&w=512)
- Maybe it should be "Publisher" instead of "Publish" - i'm just very used to seeing Publish in our tools.
- I prefer Publish at the end to emphasise the tool. 
- There was no icon for the publisher but the AYON icon kinda works here and again gives it emphasis. 
- The icons could do with a graphic design refresh at some stage.

**Review by LiborBatek — APPROVED** [review]
I did overall testing and working like charm! Not any issues found.

image

@scottmcdonnell  Great job! I do like it very much! I hope this will get into ```main``` soon ;)

@mkolar @kalisp are u fine with it? design wise...

**Comment by BigRoy** [comment]
> I dropped Experimental tools as it just opened a message box that there were none :)

I understand the decision making - but I've had a discussion with @mkolar once about removing this from other hosts as well but he argued it should stay. It's supposed to be 'globally' available to all hosts so that if in the future new experimental tools get globally available through this. However, with AYON addons now separating more into individual addons I'm not sure how much ground truth there is still to that. So just tagging @mkolar so he can do his say on this.

> All hosts should be matched to agreed icons, names and order - Maya shelf supports icons, Harmony menu too, Nuke menus support icons to left of text etc.

Agreed. Preferably host feels and look similar - same goes for if it's an AYON menu, that the ordering of the menu buttons should be pretty much the same for consistency.

E.g. in most hosts as far as I know Workfiles is not at the top, etc.

Houdini:
image

Maya:
image

> Maybe it should be "Publisher" instead of "Publish" - i'm just very used to seeing Publish in our tools.

Note that "Create" and "Publish" as provided in other applications, like Maya, Houdini screenshots I shared here both refer to the Publisher tool - but they go to a different tab of the UI.

> There was no icon for the publisher but the AYON icon kinda works here and again gives it emphasis.
> The icons could do with a graphic design refresh at some stage.

Agree on the refresh - I think then redesigning so that it's also not the AYON icon but something dedicated for publishing would be nice too.

**Review by kalisp — APPROVED** [review]
I like the look, but main decision should be on Milan.

I particularly like cleanup of index.html, thats nice :).

**Comment by scottmcdonnell** [comment]
Again personal opinion but the order can match the user journey, you start with your workfile, load in other published products, manage your inventory of loaded products and then finally publish your work for review. 

Here is a mock up that lets you change icons from [this pack](https://ant.design/components/icon) and colours
[Demo](https://stackblitz.com/edit/react-s3u6dv-bdvuwd?file=demo.tsx)
image

**Comment by LiborBatek** [comment]
> Again personal opinion but the order can match the user journey, you start with your workfile, load in other published products, manage your inventory of loaded products and then finally publish your work for review.
> 
> Here is a mock up that lets you change icons from [this pack](https://ant.design/components/icon) and colours [Demo](https://stackblitz.com/edit/react-s3u6dv-bdvuwd?file=demo.tsx) image

Nice mockups! Thanks for your ynput and time u spent!
My humble opinion:
I would say the first version of the icon set being imho better as those shapes differ in broader scale and Im not much of a fan speaking of the new ones (also when tested those in DEMO mode - the higlighting on grey didnt work for me)

the orig ones also corelates much more as they ve been used in Maya host for ie...so its a no brainer for me at least.

**Comment by iLLiCiTiT** [comment]
Please move PR to https://github.com/ynput/ayon-photoshop if is still relevant

**Pull request closed without merging**
