### PR TITLE
Maya: Create yeticache instance directly on loading a yeti rig

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Create yeticache instance directly on loading a yeti rig

## Additional info

This is similar to how loading animation rig will automatically create an animation instance for publishing any loaded character rigs, but then for yeti rigs.

## Testing notes:

1. Load a Yeti Rig
3. A working `yeticache` instance should be created that can be published easily.

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
haven't tested yet, but the code looks good to me

**Review by LiborBatek — COMMENTED** [review]
After producing ```yetiRig``` product type and trying to ```Load``` it into workfile Im getting errors  during that 

```
Traceback (most recent call last):
  File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
    load_with_repre_context(
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 779, in load
    self.process_reference(
  File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_yeti_rig.py", line 59, in process_reference
    self._create_yeti_cache_instance(nodes, variant=namespace)
  File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_yeti_rig.py", line 89, in _create_yeti_cache_instance
    create_context.create(
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\create\context.py", line 1977, in create
    creator = self._get_creator_in_create(creator_identifier)
  File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\create\context.py", line 1940, in _get_creator_in_create
    raise CreatorError(
openpype.pipeline.create.creator_plugins.CreatorError: Creator io.openpype.creators.maya.yeticache was not found
```

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Its not working on ```Load``` and I have got errrors.. see the error msg above.

**Comment by BigRoy** [comment]
> After producing `yetiRig` product type and trying to `Load` it into workfile Im getting errors during that
> 
> ```
> Traceback (most recent call last):
>   File "C:\Work\REPO\ayon-core\client\ayon_core\tools\loader\models\actions.py", line 740, in _load_representations_by_loader
>     load_with_repre_context(
>   File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\load\utils.py", line 323, in load_with_repre_context
>     return loader.load(repre_context, name, namespace, options)
>   File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\api\plugin.py", line 779, in load
>     self.process_reference(
>   File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_yeti_rig.py", line 59, in process_reference
>     self._create_yeti_cache_instance(nodes, variant=namespace)
>   File "C:\Work\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\load\load_yeti_rig.py", line 89, in _create_yeti_cache_instance
>     create_context.create(
>   File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\create\context.py", line 1977, in create
>     creator = self._get_creator_in_create(creator_identifier)
>   File "C:\Work\REPO\ayon-core\client\ayon_core\pipeline\create\context.py", line 1940, in _get_creator_in_create
>     raise CreatorError(
> openpype.pipeline.create.creator_plugins.CreatorError: Creator io.openpype.creators.maya.yeticache was not found
> ```

That's odd - it exists [here](https://github.com/ynput/ayon-core/blob/dd053686e58af01da2ac71030a0fae546de640ed/client/ayon_core/hosts/maya/plugins/create/create_yeti_cache.py#L11). Do you have that Creator disabled by any chance? Hmm, not sure that's even possible because it has no settings it seems.

Do you see the **Yeti Cache** entry on the Create tab? If you create it, select the instance in the scene and then check "Extra Attributes" in the Attribute Editor - what identifier does it show?

**Comment by BigRoy** [comment]
I can reproduce the error here with:

```python
from openpype.pipeline import registered_host
from openpype.pipeline.create import CreateContext
host = registered_host()
create_context = CreateContext(host)
create_context.create(
    creator_identifier="io.openpype.creators.maya.yeticache",
    variant="Main"
)
```

**Comment by LiborBatek** [comment]
@iLLiCiTiT just notify you as there was some interesting bug regarding openpype in ayon-core? if nothing to care about just ignore it :) thx

**Review by LiborBatek — APPROVED** [review]
Now it works fine and does what it suppose to do...

image


Just seeing the publish instance, it can easily grow loong in the naming...any idea about it? Or it doesnt matter at all? Just thinking...

And second, even tho its quite cool feature to have, will be there settings for it to optionally turn this feature ```OFF``` ?? as I can imagine so users will like it some dont (for ie to have the option to name it when creating it manually and not that implict one)

**Comment by BigRoy** [comment]
> Just seeing the publish instance, it can easily grow loong in the naming...any idea about it? Or it doesnt matter at all? Just thinking...

I believe the naming convention matches what animation instances do when loaded for a rig? I agree I don't like the naming (both here and on animation instances). I'm not sure what the best options are to fix this within the AYON ecosystem in a way that's also backwards compatible.

For Animation instances we are using custom studio setting for "product name profiles" so that the naming template for animation instances are different.

**Comment by LiborBatek** [comment]
@BigRoy It would be lovely if u can add it as a settings, thank you!

**Comment by BigRoy** [comment]
> @BigRoy It would be lovely if u can add it as a settings, thank you!

Should be done with https://github.com/ynput/ayon-core/pull/288/commits/c11c8a3cad019428e8f2201025b18608da177988

**Comment by LiborBatek** [comment]
@BigRoy Sweet! I will give it a go and possibly for merge then... thx

**Comment by LiborBatek** [comment]
I did final round of testing with Ayon settings (Maya addon) for enabling/disabling this feature and all working nicely...

When ```Create Yeti Cache Instance on Load``` being ```Enabled``` it creates the ```Publish``` instance for yeti cache and if ```Disabled`` then not creating it and its up to the users decision to create one.

Here is the setting on Ayon:
Screenshot 2024-04-19 111943

**Pull request merged**
