### PR TITLE
Chore: Removed Blender addon

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Removed Blender addon from ayon-core repository as is moved to https://github.com/ynput/ayon-blender .

### CODE REVIEW

**Review by LiborBatek — APPROVED** [review]
All seems working normally and tested with separate addon package from blender repository...

All working. LGTM

**Comment by BigRoy** [comment]
@iLLiCiTiT is there a reason this file is lacking inside `ayon-blender` which does exist in the blender addon in core?

https://github.com/ynput/ayon-core/blob/develop/server_addon/blender/client/ayon_blender/plugins/publish/collect_file_dependencies.py

Does not exist currently in develop on `ayon-blender`:

https://github.com/ynput/ayon-blender/tree/develop/client/ayon_blender/plugins/publish

**Comment by BigRoy** [comment]
Also, the fixed quadruple quotes `""""` are lacking (it's cosmetics, but might be nice to bring along)

- https://github.com/ynput/ayon-blender/blob/develop/client/ayon_blender/plugins/publish/extract_thumbnail.py#L86
- https://github.com/ynput/ayon-core/blob/develop/server_addon/blender/client/ayon_blender/plugins/publish/extract_thumbnail.py#L91

**Comment by iLLiCiTiT** [comment]
> @iLLiCiTiT is there a reason this file is lacking inside ayon-blender which does exist in the blender addon in core?

https://github.com/ynput/ayon-core/blob/develop/server_addon/blender/client/ayon_blender/plugins/publish/collect_file_dependencies.py

The file does not show any git history for me in ayon-core.

Both fixed in `ayon-blender` develop.

**Review by BigRoy — APPROVED** [review]
Workfiles, publishing, loading and managing works fine it seems.

**Pull request merged**
