### PR TITLE
Extract Review: Expose `timecode` for formatting ffmpeg args

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

This exposes the `frame_start_handle` (frame start including handles) converted to timecode like `HH:MM:SS:FF` to be used for FFMPEG args formatting.

This allows to specify e.g. `--timecode {timecode}` in the formatting arguments in settings to write the timecode metadata into the output file so that other applications can pick this up.

## Additional info

We use this for loading review files into Resolve - by having this timecode metadata included then Resolve 'understands' what the start frame / timecode is of the loaded media.

## Testing notes:

1. Add `--timecode` and `{timecode}` args to ffmpeg formatting arguments in settings
2. Publish a review.
3. The timecode metadata should be written with the output file.

### CODE REVIEW

**Comment by MustafaJafar** [comment]
I tried to test it but I failed to figure out how to test it. 
but, I could understand that we have a hard coded `timecode` data to be used when using such argument `timecode {timecode}`.

**Comment by BigRoy** [comment]
> I tried to test it but I failed to figure out how to test it. but, I could understand that we have a hard coded `timecode` data to be used when using such argument `timecode {timecode}`.

So basically, in the Extract Review settings you should be able to now add additional FFMPEG arguments that format to this timecode. Like, e.g. `ayon+settings://core/publish/ExtractReview/profiles/0/outputs/1/ffmpeg_args/output`

image

When doing that, the encoded video should have timecode metadata written along. Tools that can parse the metadata should be able to identify that - I know Resolve can read it and I suspet Premiere will be able to display it as well.

Does that help?

**Review by MustafaJafar — APPROVED** [review]
It works on myside. 

Thanks to BigRoy's comment  https://github.com/ynput/ayon-core/pull/311#issuecomment-2031350604  I was able to set the setting properly 
image

Then, I used this [website](https://www.metadata2go.com/view-metadata) to check timecode metadata. Here's how it looks
image

**Review by jakubjezek001 — APPROVED** [review]
this is awesome @BigRoy , thanks!

**Pull request merged**
