### PR TITLE
Maya: Workfile Templates implement Assign Look placeholder

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Implement a workfile template placeholder plug-in for maya that will create an object set that on populating workfile template will assign the look to all nodes inside the set, including any generated loads from other load placeholders.

This way you can dynamically automatically assign looks on loaded content in workfile templates.

## Additional info

This PR relies on:
- https://github.com/ynput/ayon-core/pull/436
- https://github.com/ynput/ayon-core/pull/425
- https://github.com/ynput/ayon-core/pull/426

I'll keep this PR as a draft until all of those are merged.

## Testing notes:

1. Create a workfile template with the assign look placeholder.
2. The placeholder should be clear to use and do what is described above.
3. The created template should work.

### CODE REVIEW

**Review by tokejepsen — DISMISSED** [review]
Looks good, but the `recursive` toggle does not seem to work:

Capture

Even with the toggle off, the look is still assigned to placeholder loaded content. Not whether we should even have this toggle? What is the use case for it?

**Review by LiborBatek — APPROVED** [review]
Works for me! Nice little feature...


Screenshot 2024-05-06 164824

Small note on ```Recursive```...didnt find a way to take it into account, as to me it always behaves recursively (its just enough to include parent groups for loaded assets to get look assign to them, which is nice in the end :)

**Comment by BigRoy** [comment]
> Even with the toggle off, the look is still assigned to placeholder loaded content. Not whether we should even have this toggle? What is the use case for it?

> Small note on `Recursive`...didnt find a way to take it into account, as to me it always behaves recursively (its just enough to include parent groups for loaded assets to get look assign to them, which is nice in the end :)

@LiborBatek @tokejepsen I think you both thought that "recursive" means "apply to all children hierarchy" and thus expected children meshes to also get assigned or not? It does not mean that. It instead means that say your workfile template, loads a file, e.g. a maya scene that in itself also has placeholders that those placeholders inside that file will also get the look assigned, recursively.

When disabled, it will only assign the look on placeholders that should've existed after the initial first load of placeholders, and not those that are recursively included from templates that were loaded in the first iteration. So that the child template being loaded it in itself can also use the assign look placeholder to 'encompass' assignments within itself that are not overridden by the parent template (or it would get overridden if the parent template is recursive, etc.

Does that clarify things?

**Comment by tokejepsen** [comment]
> Does that clarify things?

It does clarify it and its a neat feature I hadn't thought of. But think we'll need some documentation, tooltip or label description for that toggle. Would be a good way for people to discover the recursive workflow as well.

**Comment by LiborBatek** [comment]
@BigRoy really cool...also never thought this might be possible! ...I think it would be cool to discuss the templates and workflows in general...and update the user docs, as I can see there is still a lot to cover aka lots of things not covered ! (as I am finding more and more features of the templates workflow every day!)

**Comment by BigRoy** [comment]
I've made the PR compatible with the moved client code of `ayon_maya`
I've also expanded the tooltip slightly for the recursive toggle. It's not much, but may just help enough.

> But think we'll need some documentation, tooltip or label description for that toggle. Would be a good way for people to discover the recursive workflow as well.

Having documentation would be nice - but as far as I know that's a separate repo currently? Is that something you may be able to contribute knowledge for @LiborBatek - especially because recently on discord I recall you sharing some workfile template videos that might be nice there too (or even just some written demo of the general workfile templates workflow maybe?)

**Review by LiborBatek — APPROVED** [review]
All works for me!

image

I re did the tests and all seem functional. Also hints present whats the feature for...LGTM

**Pull request merged**
