### PR TITLE
Resolve: version swap retain offset and IDT

### PR DESCRIPTION
**Pull request by jakubjezek001**
## Changelog Description
Swapped version should retain the offset and IDT.

## Additional info
Ayon-core port of https://github.com/ynput/OpenPype/pull/6128 and 
closes https://github.com/ynput/OpenPype/issues/6125 issue

## Testing notes:
1. Load latest version of the clip that has Handles start > 0
2. Set any colorspace to media clip (this will need to have enabled colormanagement on Resolve project)
3. Use manage to swap for earlier version
4. Notice that colormanagement configuration is the same as the previous clip

Note that earlier version doesn't match the timeline trim of the latest version, and IDT of the version resets to default

### CODE REVIEW

**Comment by jakubjezek001** [comment]
Task linked: [OP-7981 Bug: Resolve Inventory offsets clips when swapping versions.](https://app.clickup.com/t/6658547/OP-7981)

**Review by Minkiu — APPROVED** [review]
Untested, but code looks good.

**Review by tokejepsen — CHANGES_REQUESTED** [review]
Tested in Resolve 18.6. Failed when updating the clip, but I cant find any error messages anywhere. Where would the logs go?

**Comment by jakubjezek001** [comment]
Look into Resolve's console.

**Comment by tokejepsen** [comment]
This will need resolving before we can test this; https://github.com/ynput/ayon-core/issues/160

**Comment by jakubjezek001** [comment]
> This will need resolving before we can test this; #160

this issue had been resolved from today, please try it again.

**Review by tokejepsen — APPROVED** [review]
Tested successfully in Resolve 18.6.

**Pull request merged**
