### PR TITLE
Attribute definitions: Fix FileDef value conversions

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Fix issues connected to calling `from_paths` with invalid arguments.

## Additional info
Pass to `from_paths` all required arguments.

## Testing notes:
Validate the changes in code.
1. Create `FileDef` with default value set to a path (`FileDef(..., default=["/path/to/file"])`).
2. It should not crash.

Resolves https://github.com/ynput/ayon-core/issues/991

### CODE REVIEW

**Comment by BigRoy** [comment]
The provided example `FileDef(..., default=["/path/to/file"])` does not work:

E.g.
```python
FileDef("hello", default=["/path/to/file"])
```
Results in:

```
Traceback (most recent call last):
  File "F:\dev\ayon-core\client\ayon_core\pipeline\create\context.py", line 1251, in bulk_add_instances
    attr_defs = plugin.get_attr_defs_for_instance(
  File "F:\dev\ayon-core\client\ayon_core\pipeline\publish\publish_plugins.py", line 233, in get_attr_defs_for_instance
    return cls.get_attribute_defs()
  File "F:\dev\ayon-colorbleed\client\ayon_colorbleed\plugins\publish\collect_product_group.py", line 45, in get_attribute_defs
    FileDef("hello", default=["/path/to/file"])
  File "F:\dev\ayon-core\client\ayon_core\lib\attribute_definitions.py", line 86, in __call__
    obj = super(AbstractAttrDefMeta, cls).__call__(*args, **kwargs)
  File "F:\dev\ayon-core\client\ayon_core\lib\attribute_definitions.py", line 974, in __init__
    raise TypeError((
TypeError: 'default' argument must be 'str' or 'dict' not '<class 'list'>'http://localhost:5000 "POST /graphql HTTP/1.1" 200 817
```

Passing it as string however does work:
```python
FileDef("hello", default="/path/to/file")
```

image

Is that intended behavior? @iLLiCiTiT

**Review by BigRoy — APPROVED** [review]
Actually lists do work if `single_item=False` on the attribute definition.

```python
FileDef("hello", single_item=False, default=["/path/to/file"])
```

And:
```python
FileDef("hello", single_item=False, default=["/path/to/file", "/path/to/another/other_file"])
```

image

**Comment by BigRoy** [comment]
Slight cosmetic note - if a `FileDef` has a default item in there it's not very clear how to add a new entry into it since it doesn't show the "Drag & Drop files here" message.

**Comment by iLLiCiTiT** [comment]
> Slight cosmetic note - if a FileDef has a default item in there it's not very clear how to add a new entry into it since it doesn't show the "Drag & Drop files here" message.

That might deserve an issue.

**Pull request merged**
