### PR TITLE
Deadline: Remove legacy `suspend_publish` attribute definition in favor of `publishJobState`

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Remove legacy `suspend_publish` attribute definition in favor of `publishJobState`.

The Publish Job State became exposed some time ago through a dedicated `EnumDef` replacing the 'legacy' `suspend_publish`:
image

## Additional info

n/a

## Testing notes:

1. Publishing to Deadline should be able to set publish job state and it should work:
    - [x] Houdini
    - [x] Maya (should not actually be altered)
    - [x] Fusion
    - [x] Nuke

### CODE REVIEW

**Review by MustafaJafar — APPROVED** [review]
works in Houdini

**Comment by kalisp** [comment]
Isn't working in Fusion, as instance there is just regular `render`. `render.farm` is attached only in `collect_render` plugin.

**Review by LiborBatek — COMMENTED** [review]
When tested in ```Maya 2024``` and set my ```PublishJobState``` to ```Suspended``` it just suspends the actual ```publish job``` and not the ```render job``` and immedeately start to render those...

Is that correct behaviour?? As I was expecting the job simply wont start and being suspended till user resume it...

As seen here that the render job being queing and not ```suspended``` as the publish job
Screenshot 2024-04-02 160850

**Comment by BigRoy** [comment]
> When tested in `Maya 2024` and set my `PublishJobState` to `Suspended` it just suspends the actual `publish job` and not the `render job` and immedeately start to render those...
> 
> Is that correct behaviour?? As I was expecting the job simply wont start and being suspended till user resume it...

Yes, that is the correct behavior of that particular toggle. It's only about the Publish Job - not the Render Job state.

**Comment by kalisp** [comment]
I think that in Nuke it has same issue as in Fusion, the toggle is not visible as `render.farm` is not there yet.

**Comment by BigRoy** [comment]
Ok, so I took a look at Fusion (and a bit at reading code for Nuke). I wonder how we can actually best 'target' this plug-in so that the attribute definitions show for the instances.

Fusion now has two creators, product type "image" and product type "render". To show the attribute definitions for both of those the `families` for this plug-in must contains those product types as families. However, "image" may conflict with product types in other hosts where we may NOT want to show it, maybe?

Anyway, I've added `render` and `image` and also `prerender` which I think is relevant for Nuke? The actual processing of this plug-in is skipped anyway if `instance.data["farm"]` is not true anyway.

Implemented with https://github.com/ynput/ayon-core/pull/315/commits/03cfed2c7957538a9c72afe4e31c010cb1d606ab

Would love to know if anyone sees any issues - and/or whether it works. it worked for me in Fusion, but definitely give it a test run.
And of course, test others hosts as well that use any family `render`, `image` or `prerender`.

**Comment by moonyuet** [comment]
Tested with the image instance in SP, looks good.
image

**Comment by kalisp** [comment]
This is weird (and will be weird for all local `render` or `image` publishes).
image

I don't think this is correct solution, I would prefer to move assignment of `render.farm` to creation phase for Nuke and Fusion, removal `render` product type in DL submissions altogether. 

The issue there might be if artist would switch between `Local` and `Farm` publishing, I don't think we are "repainting" toggles after that (maybe we do after `Save`? That would be enough, I think.)

**Comment by BigRoy** [comment]
> But it **does** create a publish job for it.

This is good - if the publish job works. The toggle doesn't decide whether it gets created or not - it only decides whether it starts "active" (which will be pending at first) or "suspended"

**Comment by BigRoy** [comment]
> This is weird (and will be weird for all local `render` or `image` publishes). image
> 
> I don't think this is correct solution, I would prefer to move assignment of `render.farm` to creation phase for Nuke and Fusion, removal `render` product type in DL submissions altogether.
> 
> The issue there might be if artist would switch between `Local` and `Farm` publishing, I don't think we are "repainting" toggles after that (maybe we do after `Save`? That would be enough, I think.)

No - the attribute definitions are static, and only target the main product type - not something during collect stage or any "additional families" set by the creator. As such, unfortunately this is the current "best" behavior. The attribute always shows and does not disable when it becomes irrelevant due to another toggle on the instance.

In short, unfortunately that looks correct. That is if when setting render target to FARM that the publish job toggle actually does something. I believe @antirotor has set up some issues tracking the Publisher improvements to be able to make toggles dependent on each other, etc. - I believe it's this one: https://github.com/ynput/ayon-core/issues/133

**Review by kalisp — APPROVED** [review]
I tested Nuke and Fusion, seems ok (with regard of my last comment).

**Review by MustafaJafar — APPROVED** [review]
works in Houdini

**Comment by BigRoy** [comment]
Ready to merge?

**Pull request merged**
